[package]
name = "lib-ruby-parser-ast"
version = "0.1.0"
edition = "2021"

[features]
default = []
codegen = ["lib-ruby-parser-nodes"]

[dependencies]

[build-dependencies]
lib-ruby-parser-nodes = { optional = true, version = "0.55.0" }
