ignore = [
    # codegen
    # must be in sync with .gitignore
    "src/loc_name/gen.rs",
    "src/nodes/types/*.rs",
    "src/nodes/node_enum.rs",
    "src/error/messages/message_enum.rs",
    "src/traverse/visitor/visit_gen.rs",
    "src/traverse/finder/finder_gen.rs",
]
